### ISSUE TITLE
Classification

### ISSUE THREAD

**Issue by j-bresson** [openmusic-project/Morphologie#1]
None of the 3 example patches in the "classification" folder works.
=> debug work !

**Comment by FredVoisin** [comment]
Please see [this commit](https://github.com/FredVoisin/Morphologie/commit/d0cd4efbe079865d2ce036aabf78f7eb2b5ca8cb) on my fork :)

**Comment by j-bresson** [comment]
thanks! but it seems you got a parenthesis issue around function "structure-2"


_++++ Error between functions:
  End of file while reading stream #<stream::latin-1-file-stream /Users/bresson/SRC/OM/Morphologie/sources/morphologie.lisp>._

**Comment by FredVoisin** [comment]
Fixed here: https://github.com/FredVoisin/Morphologie/commit/0a6a50538bff0c81306c254a4d0080fe6d02bb70

**Comment by j-bresson** [comment]
👍
