### ISSUE TITLE
Cleaning up the master branch commits

### ISSUE THREAD

**Issue by j-bresson** [openmusic-project/Morphologie#10]
I have had hard time fixing some file encoding and file name conflicts in the recent commits because of file renamed along with branching and merging, and so created a streamlined, cleaned up version of the 1.0->1.1 history as a new branch: https://github.com/openmusic-project/Morphologie/commits/master-cleaned-up 

@karimhaddad if this is ok for you I can force-push this as the current master and update the tags and releases accordingly.

**Comment by karimhaddad** [comment]
@j-bresson I don't have time to check if it runs on OM. But you may do it if you think it is ok for you.
My best
K

**Comment by j-bresson** [comment]
Ok, I just pushed the cleaned-up version of master. I will now work on this file encoding issue and update the 1.1 release.
