### ISSUE TITLE
Problem loading version 1.1 on Linux

### ISSUE THREAD

**Issue by karimhaddad** [openmusic-project/Morphologie#11]
I don't  know if it is an encoding matter but i get this when Morpholigie.lisp (loading library file) is loaded although i don;t seem to locate this strange character...

![Screenshot_2020-12-20_19-20-11](https://user-images.githubusercontent.com/16069737/102721385-bd4b0680-42fa-11eb-8680-9d3c86bbd89e.png)

**Comment by j-bresson** [comment]
Duplicate #6 and #9 => working on it !
