### ISSUE TITLE
Structure-2

### ISSUE THREAD

**Issue by j-bresson** [openmusic-project/Morphologie#2]
The function structure-2 crashes in some cases (see Help-patch "structures/structure-2")

**Comment by FredVoisin** [comment]
I have no crash when running second instance (the one in the middle) of structure-2 in Help-patch "structures/structure-2", but the thwo other instances (left and right side in the patch) return errors to be fixed soon.

**Comment by FredVoisin** [comment]
see [commit](https://github.com/openmusic-project/Morphologie/pull/4#issue-321592013)

**Comment by FredVoisin** [comment]
The trouble about pretty printing for structure-2 Help patch is fixed for OM7 and stills for OM6.15.
See this [commit](https://github.com/openmusic-project/Morphologie/pull/4/commits/e86de6cca06606faf4f2a074416f5170d5697226).

**Comment by j-bresson** [comment]
OM makes some modification on the default output streams which make the print / format and friends work differently than in a standard Lisp.
om-lisp::\*om-stream\* is the stream  you should address to print on the Listener with FORMAT / WRITE and other functions :  (format \*om-stream\* ...)

**Comment by FredVoisin** [comment]
ok thank's Jean.

last commit with pretty prints for all Morphologie lib updated [here](https://github.com/openmusic-project/Morphologie/pull/4/commits/f0461244a73803f18fda874533486fd484458e6d)

**Comment by j-bresson** [comment]
Sorry to borher again, but why not just using :
(PRINT "......")
instead of :
(FORMAT om-lisp::\*om-stream\* "....")

... or if you need the FORMAT utilities:

(PRINT (FORMAT NIL "......"))

This way your code would remain quite independent from such OM-specific idiom

**Comment by j-bresson** [comment]
ps. I can do it myself when I merge your fix
